FROM mcr.microsoft.com/playwright:v1.48.2-jammy

WORKDIR /work
COPY package.json package-lock.json* tsconfig.base.json .eslint* .prettier* ./
COPY packages/playwright-e2e ./packages/playwright-e2e
RUN npm ci --omit=optional && npx playwright install --with-deps
WORKDIR /work/packages/playwright-e2e
CMD ["npm","run","test"]